plugins {
    id 'java-library'
}

tasks.register('slice2java', Exec) {
    def srcDir = file("src/main/slice")
    def outDir = layout.buildDirectory.dir("generated/slice").get().asFile
    def iceFiles = fileTree(srcDir).matching { include '*.ice' }.files.collect { it.absolutePath }

    inputs.dir(srcDir)
    outputs.dir(outDir)
    doFirst { outDir.mkdirs() }

    commandLine(['slice2java', '-I', srcDir.absolutePath, '--output-dir', outDir.absolutePath] + iceFiles)
}

sourceSets.main.java.srcDir layout.buildDirectory.dir("generated/slice")
compileJava.dependsOn 'slice2java'

